baseURL: "https://ilonabodn.ar/"
languageCode: "en-us"
title: "ilona"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "ilona's profile"
  description: ilona's portfolio website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/Kuzco-Square.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/Kuzco-Square.png" # Logo for the brand | default is the favicon variable
    brandName: "ilona bodnar" # Brand name for the brand | default is the title variable
    disableSearch: true
    enableStickyHeader: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "hi, my name is"
    title: "ilona."
    subtitle: ""
    content: "I'm a fullstack developer that works mainly in React and Go. Let's get in touch."
    image: /ilona-square.png
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/pantera-rosa
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  # about:
  #   enable: true
  #   title: "About Me"
  #   image: "/images/me.png"
  #   content: |-
  #     I'm a software engineer with a passion for web development. I am currently working as a software developer 
  #     at [example org.](https://example.com) in San Francisco, CA. 

      
    # skills:
    #   enable: true
    #   title: "Here are a few technologies I've been working with recently:"
    #   items:
    #     - "HTML"
    #     - "CSS"
    #     - "JavaScript"
    #     - "React"
    #     - "Node"
    #     - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Engineer II"
        company: "NerdWallet"
        companyUrl: "https://nerdwallet.com"
        date: "Summer 2019, May 2020 - July 2022"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        info:
          enable: true
          content: Promoted from intern to SWE I and SWE I to SWE II
        content: |
          - Led conversion of  internal repositories from JS to Typescript and led conversion to Jest testing framework from Mocha
          - Improved core web vitals performance metrics across NerdWallet pages using tools like Datadog and Pagespeed, resulting in 10%+ percent reductions of page load time
          - Created React components for NerdWallet's products and instrumented them according to internal analytics requirements, using GraphQL to fetch and render data on NerdWallet pages
          - Developed and designed a changelog view for product managers to see view request history & analyze marketplace performance for partners like Chase, Capital One, and others; created the backend & API endpoints in Python and the frontend in React
          - Created automated API documentation using Swagger Docs & Python scripts on Product Platform


      - job: "Software Engineering Intern"
        company: "Google"
        companyUrl: "https://google.com"
        date: "Summer 2016, Summer 2017, Summer 2018"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: Completed 3 internships
        content: |
          - Worked on release engineering (tools & infrastructure) for Google Cloud EngProd on an internal release orchestration engine that manages flows (2018)
          - Developed and designed a configuration microservice in Java using external resources such as SpringBoot + Maven to create the application and deployed to Kubernetes Engine using Docker containers (2018)
          - Worked on Google Express team, developing a page where merchants (i.e. Costco, Target, etc) can easily and efficiently create an advertising campaign in HTML/CSS, using Dart and Angular2 technologies (2017)
          - Worked on Google Voice Assistant team, created error card in C++ to notify user when the assistant can't execute a specific action (2016)
          - Developed scripts in Python to assist developer team with merging configurations for launching and versioning features when there were overlaps (2016)

      - job: "Computer Science TA"
        company: "Pixar Animation Studios Girls Who Code"
        date: "Summer 2015"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        content: |
          - Taught fundamentals of computer science: Python, Javascript, HTML/CSS, JQuery, and the visual programming language Scratch
          - Mentored student projects, communicated with Pixar and Girls Who Code employees on speaker events and workshops


      
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "B.A. Media Arts & Practice"
        school:
          name: "University of Southern California"
          url: "https://usc.edu"
        date: "2015 - 2019"
        content: |-
          Thematic Option Honors

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Code2040 Fellow
        content: One of X software engineers in the nation selected to be a part of the Code2040 Fellowship.
        url: https://example.com
      - title: Technolochicas Campaign
        content: Face of the Technolochicas Campaign working with Televisa and the Eva Longoria Foundation to get more young Latin@s in tech.
        url: "https://www.youtube.com/watch?v=xeF7VXbDbmY"
      - title: Grace Hopper Scholarships
        content: Awarded various competitive scholarships to the Grace Hopper Conference from the National Science Foundation (2015), Google (2016, 2017), and Girls Who Code in conjunction with the Anita Borg Foundation (2019).
      - title: USC Viterbi School of Engineering Fellow
        content: Research grant and distinction awarded to top 40 incoming engineering students. Worked at the USC Robot Interaction Lab.
        url: https://viterbiadmission.usc.edu/fellows/
      - title: White House Tech Jam Invitee
        content: Spoke with educators, students, and developers to generate new ways to bring fun and engaging computer science experiences, coding, and computational thinking into K-6 classrooms.
        url: https://obamawhitehouse.archives.gov/blog/2015/12/08/administration-kicks-participation-computer-science-education-week

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: My Portfolio
        content: A bit of inception. I built this site using Hugo and contributed to the open source development of this theme.
        image: /Kuzco-Square.png
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/pantera-rosa/ilonabodn.ar

      - title: Image Converter
        content: asdf
        image: /Kuzco-Square.png
        featured:
          name: Demo
          link: https://ilonabodn.ar
        badges:
          - "Go"
          - "MySQL"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ch7bacgqb7@privaterelay.appleid.com
    btnName: Email
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/pantera-rosa
      linkedin: https://linkedin.com/in/ilonabodnar
      twitter: https://twitter.com
      instagram: https://instagram.com/la.vida.de.ilo

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
    
  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
